language: php
sudo: required

services:
  - memcached
  - redis-server
  - mysql

php:
  - '5.5'
  - '5.6'
#  - '7.0'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'

mysql:
  database: phwoolcon_test
  username: travis
  encoding: utf8mb4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh

before_script:
  - composer self-update
  - composer update --no-interaction --prefer-source
  - mysql -uroot -e 'CREATE DATABASE `phwoolcon_test` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;'
  - phpenv config-add php-ext.ini
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs
  - phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
