language: php
sudo: required

services:
  - memcached
  - redis-server
  - mysql

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.1'

mysql:
  database: phwoolcon_test
  username: travis
  encoding: utf8mb4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon

before_install:
  - sudo apt-get update -qq
  # Install Beanstalkd (Queue support)
  - sudo apt-get install -qq beanstalkd
  # Install Postfix (SMTP mailer support)
  - sudo apt-get install -y -qq postfix
  # Use test mail server
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  # Disable sendmail
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  # Update composer
  - composer self-update
  # Install imagick to pass Phalcon compiling
  - printf "\n" | pecl install imagick
  # Install Swoole
  - pecl install swoole
  - phpenv config-add php-ext.ini
  # Install Phalcon
  - bin/ci-install-phalcon
  # Install Phwoolcon
  - composer install --prefer-source --no-interaction
  # Install phpcs
  - pear install PHP_CodeSniffer
  - phpenv rehash

before_script:
  # Update dependencies
  - composer update --no-interaction --prefer-source
  # Create database
  - mysql -uroot -e 'CREATE DATABASE `phwoolcon_test` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;'
  # Print Phalcon and Swoole info
  - php --ri phalcon
  - php --ri swoole

script:
  # Check code style
  - phpcs
  # Running unit test
  - phpunit --verbose --coverage-clover=coverage.xml

after_success:
  # Collect code coverage
  - bash <(curl -s https://codecov.io/bash)

branches:
  #Don't build tags
  except:
  - /^v\d/
